# Site settings
title: Die Full Service Werbeagentur Köln – ep-communication.de

description: "Strategie, Kreation & Realisierung von effektiven Ideen, die begeistern: für B2B & B2C, online & offline #weilwireskönnen"
baseurl: "epcommunication/" # the base hostname & protocol for your site
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

collections:
  projects:
    output: true
  jobs:
    output: true

_comments:
  tags: "Auflistung mit Komma trennen"
