company_name: ep communication GmbH
ceo: Emitis Pohl
adress: Bayenthalgürtel 7
plz: 50968 Köln
amtsgericht: Köln HRB 76168
ust_id: DE284 154 502
tel: +49 (0)221 96 98 95-90
fax: +49 (0)221 96 98 95-96
contact_email: info@ep-communication.de
facebook: 'https://www.facebook.com/epcommunicationgmbh'
xing: 'https://www.xing.com/companies/epcommunicationgmbh'
twitter: 'https://twitter.com/ep_comm_gmbh'
instagram: 'https://www.instagram.com/epcommunication/'
youtube: 'https://www.youtube.com/user/epcommunication'
google_analytics_id: UA-67738164-2